// Mocks generated by Mockito 5.4.6 from annotations
// in sapiensshifter/test/notificiation_token_manager_test/notification_token_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:core/src/interfaces/interface.dart' as _i2;
import 'package:core/src/models/base_model_interface.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeINetworkOperation_0 extends _i1.SmartFake
    implements _i2.INetworkOperation {
  _FakeINetworkOperation_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeILocalCacheOperation_1 extends _i1.SmartFake
    implements _i2.ILocalCacheOperation {
  _FakeILocalCacheOperation_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_2<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [INetworkManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockINetworkManager extends _i1.Mock implements _i2.INetworkManager {
  @override
  _i2.INetworkOperation get networkOperation => (super.noSuchMethod(
        Invocation.getter(#networkOperation),
        returnValue: _FakeINetworkOperation_0(
          this,
          Invocation.getter(#networkOperation),
        ),
        returnValueForMissingStub: _FakeINetworkOperation_0(
          this,
          Invocation.getter(#networkOperation),
        ),
      ) as _i2.INetworkOperation);

  @override
  void init() => super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ILocalCacheManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockILocalCacheManager extends _i1.Mock
    implements _i2.ILocalCacheManager {
  @override
  _i2.ILocalCacheOperation get cacheOperation => (super.noSuchMethod(
        Invocation.getter(#cacheOperation),
        returnValue: _FakeILocalCacheOperation_1(
          this,
          Invocation.getter(#cacheOperation),
        ),
        returnValueForMissingStub: _FakeILocalCacheOperation_1(
          this,
          Invocation.getter(#cacheOperation),
        ),
      ) as _i2.ILocalCacheOperation);

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> remove() => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [ILocalCacheOperation].
///
/// See the documentation for Mockito's code generation for more information.
class MockILocalCacheOperation extends _i1.Mock
    implements _i2.ILocalCacheOperation {
  @override
  _i3.Future<bool> write<T>({
    required String? key,
    required T? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [],
          {
            #key: key,
            #value: value,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> writeAll({required Map<String, dynamic>? items}) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeAll,
          [],
          {#items: items},
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<MapEntry<String, T>> getValue<T>({required String? key}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getValue,
          [],
          {#key: key},
        ),
        returnValue: _i3.Future<MapEntry<String, T>>.value(
            _i4.dummyValue<MapEntry<String, T>>(
          this,
          Invocation.method(
            #getValue,
            [],
            {#key: key},
          ),
        )),
        returnValueForMissingStub: _i3.Future<MapEntry<String, T>>.value(
            _i4.dummyValue<MapEntry<String, T>>(
          this,
          Invocation.method(
            #getValue,
            [],
            {#key: key},
          ),
        )),
      ) as _i3.Future<MapEntry<String, T>>);

  @override
  _i3.Future<Map<String, dynamic>> getAllValue() => (super.noSuchMethod(
        Invocation.method(
          #getAllValue,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<bool> delete({required String? key}) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {#key: key},
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> updateValue({
    required String? key,
    required dynamic newValue,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateValue,
          [],
          {
            #key: key,
            #newValue: newValue,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [INetworkOperation].
///
/// See the documentation for Mockito's code generation for more information.
class MockINetworkOperation extends _i1.Mock implements _i2.INetworkOperation {
  @override
  _i3.Future<T> getItem<T extends _i5.IBaseModel<T>>({
    required String? path,
    required T? model,
    String? key,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItem,
          [],
          {
            #path: path,
            #model: model,
            #key: key,
          },
        ),
        returnValue: _i4.ifNotNull(
              _i4.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #getItem,
                  [],
                  {
                    #path: path,
                    #model: model,
                    #key: key,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #getItem,
                [],
                {
                  #path: path,
                  #model: model,
                  #key: key,
                },
              ),
            ),
        returnValueForMissingStub: _i4.ifNotNull(
              _i4.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #getItem,
                  [],
                  {
                    #path: path,
                    #model: model,
                    #key: key,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #getItem,
                [],
                {
                  #path: path,
                  #model: model,
                  #key: key,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<List<T>> getItemsQuery<T extends _i5.IBaseModel<T>>({
    required String? path,
    required T? model,
    String? key,
    _i2.INetworkQuery? query,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsQuery,
          [],
          {
            #path: path,
            #model: model,
            #key: key,
            #query: query,
          },
        ),
        returnValue: _i3.Future<List<T>>.value(<T>[]),
        returnValueForMissingStub: _i3.Future<List<T>>.value(<T>[]),
      ) as _i3.Future<List<T>>);

  @override
  _i3.Future<bool> itemExists({required String? path}) => (super.noSuchMethod(
        Invocation.method(
          #itemExists,
          [],
          {#path: path},
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> addItem<T extends _i5.IBaseModel<T>>({
    required String? path,
    required T? item,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addItem,
          [],
          {
            #path: path,
            #item: item,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> addAllItem<T extends _i5.IBaseModel<T>>({
    required String? path,
    required List<T>? items,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAllItem,
          [],
          {
            #path: path,
            #items: items,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> update({
    required String? path,
    required Map<String, dynamic>? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {
            #path: path,
            #value: value,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> updateAll<T extends _i5.IBaseModel<T>>({
    required String? path,
    required List<T>? items,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAll,
          [],
          {
            #path: path,
            #items: items,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> replaceItem<T extends _i5.IBaseModel<T>>({
    required String? path,
    required T? item,
    String? key,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceItem,
          [],
          {
            #path: path,
            #item: item,
            #key: key,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteItem({
    required String? path,
    String? key,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [],
          {
            #path: path,
            #key: key,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Stream<T> getStream<T extends _i5.IBaseModel<T>>({
    required String? path,
    required T? model,
    String? key,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStream,
          [],
          {
            #path: path,
            #model: model,
            #key: key,
          },
        ),
        returnValue: _i3.Stream<T>.empty(),
        returnValueForMissingStub: _i3.Stream<T>.empty(),
      ) as _i3.Stream<T>);

  @override
  _i3.Stream<List<T>> getStreamQuery<T extends _i5.IBaseModel<T>>({
    required String? path,
    required T? model,
    String? key,
    _i2.INetworkQuery? query,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStreamQuery,
          [],
          {
            #path: path,
            #model: model,
            #key: key,
            #query: query,
          },
        ),
        returnValue: _i3.Stream<List<T>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<T>>.empty(),
      ) as _i3.Stream<List<T>>);
}
