// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7cu7mtaQj_8-dldZdQObxXttA3XBXULI',
    appId: '1:497068609218:android:ef86a43b688c4313a0755b',
    messagingSenderId: '497068609218',
    projectId: 'coffeesapiens',
    databaseURL: 'https://coffeesapiens-default-rtdb.firebaseio.com',
    storageBucket: 'coffeesapiens.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5CTcF55qYHunpczUWvr_2dE5osSVdreE',
    appId: '1:497068609218:ios:70cf16b37567ee9aa0755b',
    messagingSenderId: '497068609218',
    projectId: 'coffeesapiens',
    databaseURL: 'https://coffeesapiens-default-rtdb.firebaseio.com',
    storageBucket: 'coffeesapiens.firebasestorage.app',
    androidClientId: '497068609218-7kjvcoeg670mvhp2dkfcs1030gu9e9m5.apps.googleusercontent.com',
    iosClientId: '497068609218-1m0kcejg0l4hkhij7sit31ql8eicmsvl.apps.googleusercontent.com',
    iosBundleId: 'com.coffeesapiens.sapiensshifter',
  );

}