name: sapiensshifter
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  #Core
  core:
    path: module/core

  #Auth
  firebase_auth_module:
    path: module/firebase/firebase_auth_module

  #Database
  firebase_firestore_module:
    path: module/firebase/firebase_firestore_module

  #Local Cache
  sharhed_preferences_module:
    path: module/local_cache/sharhed_preferences_module

  #Utilts
  sizer: ^3.0.5
  flutter_svg: ^2.0.16
  kartal: ^4.1.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0

  #Firebase
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.2

  #Social Sign
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4

  #Network
  http: ^1.2.2

  #Local Storage
  shared_preferences: ^2.5.2

  #UI
  animated_custom_dropdown: ^3.1.1
  flutter_slidable: ^3.1.2

  #Localization
  easy_localization: ^3.0.7

  cupertino_icons: ^1.0.8
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  #Analysis
  very_good_analysis: ^6.0.0

  #Generator
  build_runner: ^2.3.3
  json_serializable: ^6.8.0

  #Test
  mockito: ^5.4.5


flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/logo/
    - assets/translations/

  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Thin.otf
          weight: 100
        - asset: assets/fonts/Geist-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Geist-Light.otf
          weight: 300
        - asset: assets/fonts/Geist-Regular.otf
          weight: 400
        - asset: assets/fonts/Geist-Medium.otf
          weight: 500
        - asset: assets/fonts/Geist-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Geist-Bold.otf
          weight: 700
        - asset: assets/fonts/Geist-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Geist-Black.otf
          weight: 900          