name: sapiensshifter
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  #Core
  core:
    path: module/core

  #Auth
  firebase_auth_module:
    path: module/firebase/firebase_auth_module

  #Database
  firebase_firestore_module:
    path: module/firebase/firebase_firestore_module

  #Local Cache
  sharhed_preferences_module:
    path: module/local_cache/sharhed_preferences_module

  #Storage
  firebase_storage_module:
    path: module/firebase/firebase_storage_module

  #Utilts
  sizer: ^3.0.5
  flutter_svg: ^2.0.16
  equatable: ^2.0.7
  kartal: ^4.1.0
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  uuid: ^4.5.1
  intl: ^0.20.2
  mime: ^1.0.6
  image: ^4.5.4

  #Log
  logging: ^1.3.0

  #Firebase
  firebase_core: ^3.10.0
  firebase_messaging: ^15.1.4
  cloud_firestore: ^5.6.2

  #State
  flutter_bloc: ^9.0.0
  flutter_riverpod: ^2.6.1

  #Network
  http: ^1.2.2

  #UI
  animated_custom_dropdown: ^3.1.1
  flutter_slidable: ^4.0.0
  smooth_page_indicator: ^1.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  

  #Localization
  easy_localization: ^3.0.7

  #Route
  auto_route: ^10.0.1

  #Notification
  flutter_local_notifications: ^19.0.0

  cupertino_icons: ^1.0.8
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  #Analysis
  very_good_analysis: ^7.0.0

  #Generator
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  auto_route_generator: ^10.0.1

  #Test
  mockito: ^5.4.6


flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/icon/order_status_ic/
    - assets/icon/social_sign_ic/
    - assets/logo/
    - assets/images/
    - assets/images/onboard/
    - assets/translations/

  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Thin.otf
          weight: 100
        - asset: assets/fonts/Geist-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Geist-Light.otf
          weight: 300
        - asset: assets/fonts/Geist-Regular.otf
          weight: 400
        - asset: assets/fonts/Geist-Medium.otf
          weight: 500
        - asset: assets/fonts/Geist-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Geist-Bold.otf
          weight: 700
        - asset: assets/fonts/Geist-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Geist-Black.otf
          weight: 900          