name: firebase_firestore_module
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

  #Core Package
  core:
    path: ../../core

  #Firebase
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
